package tc500s.tc592;
import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class LittleElephantAndBalls
{
	public int getNumber(String S)
	{
		int r = 0;
		int g = 0;
		int b = 0;
		int len = S.length();
		
		int ret = 0;
		for (int i = 0; i < len; i++) {
			if (S.charAt(i) == 'R') {
				ret += r + g + b;
				r = Math.min(2, r + 1);
			}
			if (S.charAt(i) == 'G') {
				ret += r + g + b;
				g = Math.min(2, g + 1);
			}
			if (S.charAt(i) == 'B') {
				ret += r + g + b;
				b = Math.min(2, b + 1);
			}
		}
		return ret;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit-pf 2.3.0
	private static boolean KawigiEdit_RunTest(int testNum, String p0, boolean hasAnswer, int p1) {
		System.out.print("Test " + testNum + ": [" + "\"" + p0 + "\"");
		System.out.println("]");
		LittleElephantAndBalls obj;
		int answer;
		obj = new LittleElephantAndBalls();
		long startTime = System.currentTimeMillis();
		answer = obj.getNumber(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p1);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p1;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		boolean disabled;
		boolean tests_disabled;
		all_right = true;
		tests_disabled = false;
		
		String p0;
		int p1;
		
		// ----- test 0 -----
		disabled = false;
		p0 = "RGB";
		p1 = 3;
		all_right = (disabled || KawigiEdit_RunTest(0, p0, true, p1) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 1 -----
		disabled = false;
		p0 = "RGGRBBB";
		p1 = 21;
		all_right = (disabled || KawigiEdit_RunTest(1, p0, true, p1) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 2 -----
		disabled = false;
		p0 = "RRRGBRR";
		p1 = 16;
		all_right = (disabled || KawigiEdit_RunTest(2, p0, true, p1) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 3 -----
		disabled = false;
		p0 = "RRRR";
		p1 = 5;
		all_right = (disabled || KawigiEdit_RunTest(3, p0, true, p1) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 4 -----
		disabled = false;
		p0 = "GGRRRGR";
		p1 = 18;
		all_right = (disabled || KawigiEdit_RunTest(4, p0, true, p1) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 5 -----
		disabled = false;
		p0 = "G";
		p1 = 0;
		all_right = (disabled || KawigiEdit_RunTest(5, p0, true, p1) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		if (all_right) {
			if (tests_disabled) {
				System.out.println("You're a stud (but some test cases were disabled)!");
			} else {
				System.out.println("You're a stud (at least on given cases)!");
			}
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// PROBLEM STATEMENT
	// 
	// Little Elephant from the Zoo of Lviv likes balls.
	// He has some balls that he wants to arrange into a row on the table.
	// Each of those balls has one of three possible colors: red, green, or blue.
	// 
	// 
	// 
	// 
	// You are given a String S.
	// This string represents all of the balls Little Elephant has, in the order in which he will be placing them onto the table.
	// Red, green, and blue balls are represented by the characters 'R', 'G', and 'B', respectively.
	// Each time Little Elephant places a new ball onto the table, he may add it anywhere into the row of already placed balls.
	// 
	// 
	// 
	// 
	// Additionally, each time Little Elephant adds a ball to the table, he scores some points (possibly zero).
	// The number of points is calculated as follows:
	// 
	// If this is the first ball being placed on the table, there are 0 points for it.
	// If he adds the current ball to one of the ends of the row, the number of points scored is equal to the number of different colors of the balls on the table, excluding the current ball.
	// If he adds the current ball between two other balls, the number of points scored is equal to the number of different colors of the balls before the current ball, plus the number of different colors of the balls after the current ball.
	// 
	// 
	// 
	// 
	// 
	// For example, suppose that the balls currently on the table form the row "GBBG". 
	// Little Elephant now wants to add a new red ball ('R').
	// One of the options is to add it to the beginning.
	// This scores 2 points and produces the row "RGBBG".
	// Another option is to add it between "GBB" and "G".
	// There are 2 distinct colors in "GBB" and 1 in "G", so this move is worth 2+1 = 3 points.
	// This move produces the row "GBBRG".
	// 
	// 
	// 
	// 
	// Return the maximum total number of points that Little Elephant can earn for placing the balls onto the table.
	// 
	// 
	// DEFINITION
	// Class:LittleElephantAndBalls
	// Method:getNumber
	// Parameters:String
	// Returns:int
	// Method signature:int getNumber(String S)
	// 
	// 
	// CONSTRAINTS
	// -S will contain between 1 and 50 characters, inclusive.
	// -S will consist only of characters 'R', 'G' and 'B'.
	// 
	// 
	// EXAMPLES
	// 
	// 0)
	// "RGB"
	// 
	// Returns: 3
	// 
	// Any strategy is optimal here. Each strategy scores 0+1+2 = 3 points.
	// 
	// 1)
	// "RGGRBBB"
	// 
	// Returns: 21
	// 
	// 
	// 
	// 2)
	// "RRRGBRR"
	// 
	// Returns: 16
	// 
	// 
	// 
	// 3)
	// "RRRR"
	// 
	// Returns: 5
	// 
	// 
	// 
	// 4)
	// "GGRRRGR"
	// 
	// Returns: 18
	// 
	// 
	// 
	// 5)
	// "G"
	// 
	// Returns: 0
	// 
	// 
	// 
	// END KAWIGIEDIT TESTING
}

//Powered by KawigiEdit-pf 2.3.0!
